from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='Spare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(db_index=True, max_length=100)),
                ('orden_compra', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('modelo', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_material', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_art', models.CharField(blank=True, max_length=100, null=True)),
                ('descrip_gpo_art', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_valoracion', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_el_sap', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por_sap', models.CharField(blank=True, max_length=100, null=True)),
                ('sujeto_lote', models.CharField(blank=True, max_length=10, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_naciones', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_art_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_subcat', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_subcat', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil_numserie', models.CharField(blank=True, max_length=100, null=True)),
                ('marcado_borrar', models.CharField(blank=True, max_length=10, null=True)),
                ('texto_pedido', models.CharField(blank=True, max_length=300, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('centro', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_averia', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('valor_lote', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo_asignacion', models.CharField(blank=True, max_length=300, null=True)),
                ('estatus', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'spare', 'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='SAPCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(db_index=True, max_length=100, unique=True)),
                ('texto_breve', models.TextField(blank=True, null=True)),
                ('denom_tpmt', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_material', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_art', models.CharField(blank=True, max_length=100, null=True)),
                ('descrip_gpo_art', models.CharField(blank=True, max_length=200, null=True)),
                ('cat_valoracion', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_el', models.CharField(blank=True, max_length=50, null=True)),
                ('sujeto_lote', models.CharField(blank=True, max_length=10, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('etiqueta', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_naciones', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo_art_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_subcat', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_subcat', models.CharField(blank=True, max_length=200, null=True)),
                ('perfil_numserie', models.CharField(blank=True, max_length=100, null=True)),
                ('marcado_borrar', models.CharField(blank=True, max_length=10, null=True)),
                ('texto_pedido', models.CharField(blank=True, max_length=300, null=True)),
                ('fuente', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'sap_catalog'},
        ),
        migrations.CreateModel(
            name='CentroAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=50)),
                ('almacen', models.CharField(max_length=50)),
            ],
            options={'db_table': 'centro_almacen', 'ordering': ['centro', 'almacen']},
        ),
        migrations.AddConstraint(
            model_name='centroalmacen',
            constraint=models.UniqueConstraint(fields=['centro', 'almacen'], name='unique_centro_almacen'),
        ),
        migrations.CreateModel(
            name='SAPMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('material', models.CharField(db_index=True, max_length=100)),
                ('texto_breve', models.TextField(blank=True, null=True)),
                ('centro', models.CharField(blank=True, max_length=50, null=True)),
                ('almacen', models.CharField(blank=True, max_length=50, null=True)),
                ('status_sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('lote_stock', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_stock', models.CharField(blank=True, max_length=100, null=True)),
                ('modificado_el', models.DateField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('modificado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_el', models.DateField(blank=True, null=True)),
                ('equipo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'db_table': 'sap_material'},
        ),
    ]
